global:
    settings:
        dinkly_version: "2.02"
        date_format: m-d-Y h:ia

    apps:
        frontend:
            default_app: true
            default_module: landing
            base_href: /
            app_name: Dinkly Frontend
            app_description: The humble little PHP MVC Framework
        admin:
            default_module: home
            base_href: /admin
            app_name: Dinkly Admin
            app_description: The humble little PHP MVC Framework
            copyright: Dinkly
        api:
            app_name: Dinkly API
            base_href: /api
            default_module: api

    databases:
        dinkly:
            host: localhost
            user: root
            pass: root
            name: dinkly_app

        unit_test:
            host: localhost
            user: root
            pass: root
            name: dinkly_unit_test
dev:
    apps:
        admin:
            app_name: Dinkly Admin Dev
prod:
    apps:
        admin:
            app_name: Dinkly Admin